/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/app/**/*.{js,ts,jsx,tsx}', './src/components/**/*.{js,ts,jsx,tsx}', './src/pages/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#390c00',
        outline: '#8c90a1',
        'surface-dim': '#111125',
        'on-primary-fixed': '#001849',
        'surface-container-high': '#28283d',
        'secondary-fixed-dim': '#d2bbff',
        'surface-container-lowest': '#0c0c1f',
        'inverse-surface': '#e2e0fc',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-container': '#cc4204',
        'inverse-on-surface': '#2f2e43',
        'surface-container': '#1e1e32',
        'inverse-primary': '#0054d6',
        background: '#111125',
        error: '#ffb4ab',
        'surface-container-highest': '#333348',
        'primary-container': '#0066ff',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-secondary-container': '#c9aeff',
        'on-surface': '#e2e0fc',
        primary: '#b3c5ff',
        'on-primary-fixed-variant': '#003fa4',
        surface: '#111125',
        'error-container': '#93000a',
        'on-primary': '#002b75',
        'outline-variant': '#424656',
        'surface-bright': '#37374d',
        'on-surface-variant': '#c2c6d8',
        secondary: '#d2bbff',
        'tertiary-fixed-dim': '#ffb59d',
        'on-background': '#e2e0fc',
        'surface-container-low': '#1a1a2e',
        'surface-variant': '#333348',
        'on-primary-container': '#f8f7ff',
        'on-error': '#690005',
        'on-secondary-fixed': '#25005a',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'secondary-container': '#6001d1',
        'on-tertiary-fixed-variant': '#832600',
        'surface-tint': '#b3c5ff',
        'on-tertiary-container': '#fff6f4',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#eaddff',
        tertiary: '#ffb59d',
        'on-tertiary': '#5d1900',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
